#!/bin/bash
set -e

APP_NAME="OpenPaw"
BUILD_DIR=".build/debug"
APP_BUNDLE="${BUILD_DIR}/${APP_NAME}.app"

# Generate build timestamp
BUILD_DATE=$(date '+%Y-%m-%d %H:%M:%S')
cat > Sources/OpenPaw/App/BuildInfo.swift << EOF
// Auto-generated by build-app.sh — do not edit
enum BuildInfo {
    static let timestamp = "$BUILD_DATE"
}
EOF

# Build
swift build

# Create .app bundle structure
rm -rf "$APP_BUNDLE"
mkdir -p "${APP_BUNDLE}/Contents/MacOS"
mkdir -p "${APP_BUNDLE}/Contents/Resources"

# Copy binary
cp "${BUILD_DIR}/${APP_NAME}" "${APP_BUNDLE}/Contents/MacOS/"

# Generate .icns from app-icon-512p.png (512x512 with transparency)
ICON_SRC="Resources/app-icon-512p.png"
ICONSET_DIR=$(mktemp -d)/AppIcon.iconset
mkdir -p "$ICONSET_DIR"
sips -z 16 16     "$ICON_SRC" --out "${ICONSET_DIR}/icon_16x16.png"      > /dev/null 2>&1
sips -z 32 32     "$ICON_SRC" --out "${ICONSET_DIR}/icon_16x16@2x.png"   > /dev/null 2>&1
sips -z 32 32     "$ICON_SRC" --out "${ICONSET_DIR}/icon_32x32.png"      > /dev/null 2>&1
sips -z 64 64     "$ICON_SRC" --out "${ICONSET_DIR}/icon_32x32@2x.png"   > /dev/null 2>&1
sips -z 128 128   "$ICON_SRC" --out "${ICONSET_DIR}/icon_128x128.png"    > /dev/null 2>&1
sips -z 256 256   "$ICON_SRC" --out "${ICONSET_DIR}/icon_128x128@2x.png" > /dev/null 2>&1
sips -z 256 256   "$ICON_SRC" --out "${ICONSET_DIR}/icon_256x256.png"    > /dev/null 2>&1
sips -z 512 512   "$ICON_SRC" --out "${ICONSET_DIR}/icon_256x256@2x.png" > /dev/null 2>&1
cp "$ICON_SRC"    "${ICONSET_DIR}/icon_512x512.png"
cp "$ICON_SRC"    "${ICONSET_DIR}/icon_512x512@2x.png"
iconutil -c icns "$ICONSET_DIR" -o "${APP_BUNDLE}/Contents/Resources/AppIcon.icns"
rm -rf "$(dirname "$ICONSET_DIR")"

# Create Info.plist
cat > "${APP_BUNDLE}/Contents/Info.plist" << 'PLIST'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleIdentifier</key>
    <string>com.openpaw.app</string>
    <key>CFBundleName</key>
    <string>OpenPaw</string>
    <key>CFBundleDisplayName</key>
    <string>OpenPaw</string>
    <key>CFBundleExecutable</key>
    <string>OpenPaw</string>
    <key>CFBundleVersion</key>
    <string>1</string>
    <key>CFBundleShortVersionString</key>
    <string>1.0</string>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>LSMinimumSystemVersion</key>
    <string>14.0</string>
    <key>CFBundleIconFile</key>
    <string>AppIcon</string>
    <key>NSHighResolutionCapable</key>
    <true/>
    <key>LSUIElement</key>
    <false/>
    <key>NSAppTransportSecurity</key>
    <dict>
        <key>NSAllowsArbitraryLoads</key>
        <true/>
    </dict>
</dict>
</plist>
PLIST

# Codesign with entitlements
codesign --force --sign - --entitlements OpenPaw.entitlements "${APP_BUNDLE}/Contents/MacOS/${APP_NAME}"

# Copy to dist
mkdir -p dist
cp -Rf "$APP_BUNDLE" dist/

echo "Built: ${APP_BUNDLE} → dist/"
